id: A1775747E
base_file: f70E5.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:28:40.762347
  last_modified_at: 2022-06-19 17:28:40.762354
