id: A1775747E
base_file: f7284.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:28:40.765016
  last_modified_at: 2022-06-19 17:28:40.765033
