id: A1775747E
base_file: f286C.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:28:40.726749
  last_modified_at: 2022-06-19 17:28:40.726756
