id: A1775747E
base_file: f6040.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:28:40.747929
  last_modified_at: 2022-06-19 17:28:40.747945
