id: A1775747E
base_file: fFDE8.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:28:40.821842
  last_modified_at: 2022-06-19 17:28:40.821845
