id: A1775747E
base_file: fA46A.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:28:40.796300
  last_modified_at: 2022-06-19 17:28:40.796306
