id: A1775747E
base_file: fC0C4.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:28:40.803914
  last_modified_at: 2022-06-19 17:28:40.803917
