id: A1775747E
base_file: f50F7.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:28:40.742998
  last_modified_at: 2022-06-19 17:28:40.743007
