id: A1775747E
base_file: f4245.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:28:40.730852
  last_modified_at: 2022-06-19 17:28:40.730858
