id: A1775747E
base_file: f6FCA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:28:40.758804
  last_modified_at: 2022-06-19 17:28:40.758814
