id: A1775747E
base_file: f8144.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:28:40.784107
  last_modified_at: 2022-06-19 17:28:40.784124
